# Generated by Django 5.1.6 on 2025-02-14 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.TextField(default='')),
                ('subheadline', models.TextField(default='')),
                ('quote', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=100)),
                ('location_image', models.TextField(default='')),
                ('destination', models.CharField(max_length=100)),
                ('destination_slug', models.SlugField(blank=True, max_length=100)),
                ('duration', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interests', models.TextField()),
                ('overview_introduction', models.TextField()),
                ('overview_time_to_visit', models.TextField()),
                ('top_attractions', models.TextField()),
                ('interest_attractions', models.TextField()),
                ('itinerary_plan', models.JSONField(default=list)),
                ('images_by_day', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField(default=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
