# Generated by Django 5.1.6 on 2025-02-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_itinerary_text_itinerary_interest_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='headline',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='images_by_day',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='location_image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='quote',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='subheadline',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_plan',
            field=models.JSONField(default=list),
        ),
    ]
