# Generated by Django 5.1.6 on 2025-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_itinerary_destination_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='destination_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
